name: BTC Tabdeal WebSocket Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install websocket
        run: pip install websocket-client

      - name: Run WebSocket test
        run: timeout 60 python tabdeal_btc_ws_test.py
